# Generated by Django 4.1.3 on 2023-03-31 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=50, verbose_name='쿠폰 이름')),
                ('coupon_num', models.TextField(verbose_name='쿠폰번호')),
                ('available', models.BooleanField(default=True, verbose_name='사용가능여부')),
                ('charging_point', models.IntegerField(verbose_name='적립금액')),
            ],
        ),
        migrations.CreateModel(
            name='UsedCouponList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('using_coupon_time', models.DateTimeField(auto_now_add=True, verbose_name='쿠폰사용 시간')),
                ('coupon_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_coupon_name', to='payment.couponlist', verbose_name='쿠폰 이름')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_user_id', to=settings.AUTH_USER_MODEL, verbose_name='쿠폰사용유저')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='결제 목적')),
                ('amount', models.IntegerField(verbose_name='결제 금액')),
                ('payment_time', models.TextField(verbose_name='결제 시간')),
                ('usage_time', models.TextField(blank=True, verbose_name='사용 시간')),
                ('imp_uid', models.CharField(blank=True, max_length=100, verbose_name='결제번호')),
                ('merchant_uid', models.CharField(blank=True, max_length=100, verbose_name='주문번호')),
                ('buyer_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='결제한 유저')),
                ('usage_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usage.usage', verbose_name='사용 번호')),
            ],
        ),
    ]
