# Generated by Django 4.1.3 on 2023-04-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='imp_uid',
            field=models.TextField(blank=True, verbose_name='결제번호'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='merchant_uid',
            field=models.TextField(blank=True, verbose_name='주문번호'),
        ),
    ]
