# Generated by Django 4.1.3 on 2023-03-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=50, unique=True, verbose_name='아이디')),
                ('password', models.CharField(max_length=30, verbose_name='비밀번호')),
                ('billing_key', models.TextField(blank=True, null=True, verbose_name='빌링 키')),
                ('point', models.IntegerField(default=0, verbose_name='포인트')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
